runtime: custom
env: flex

service: default
manual_scaling:
  instances: 1

runtime_config:
  docker:
    image:'gcr.io/prediccionpisosia/prediccion-pisos:0.0.2'

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 20
